### ISSUE TITLE
Rename this repo to Replicator

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/replicator#844]
This issues is a list of tasks that need to be completed to complete the transition of this repo to the updated name.
Internal slack channel to coordinate tasks:  https://cockroachlabs.slack.com/archives/C072J7F32TB

## Github

- [x] Perform the repo rename
- [x] Remove unused `CDC_SINK*` secrets and vars

## Code

- [x] Update `go.mod` and all import paths - #848
- [x] PR to allow existing installations to keep using the `_cdc_sink` staging DB name - #850
- [x] Support importing the typescript api through either name (#849)
- [x] Build artifact renaming (#855)
- [x] Update build tarball destinations (#855)
- [x] Find all internal instances of cdc-sink and rename them
  - [x] jwt - #859
  - [x] CDC_SINK_TEMPLATES - #853 
  - [x] Update DockerHub build and push
  - [x] Rename binary within docker images (#869)
- [x] Scripts
  - [x] Active/Active -#871
  - [x] Shell Demo - #856
  - [x] docker_c2c - #874
  - [x] dashboard - #870

## Wiki

- [x] Find and replace all instances of cdc-sink (that are not auto generated)
- [x] Update installing page to point to the new docker hub location
- [x] Update installing page to point to the bucket location

## Binaries

- [x] Create a new bucket with the correct name https://storage.googleapis.com/replicator-binaries/ - https://github.com/cockroachlabs/crl-infrastructure/pull/1897 
- [x] Consider copying all the older binaries to the new one
- [ ] Deprecate the older bucket https://storage.googleapis.com/cdc-sink-binaries/ -- possibly publish a final binary that just throws an error pointing to the new bucket
- [x] Move the OIC binaries from https://storage.googleapis.com/cdc-sink-binaries/third_party/instantclient-basiclite-linux-amd64.zip to the new bucket.

## Docker 
- [x] Create https://hub.docker.com/r/cockroachdb/replicator 
- [ ] Depreciate the old docker hub - https://hub.docker.com/r/cockroachdb/cdc-sink -- possibly publish a final binary that just throws an error pointing to the new bucket
- [x] Publish to a new docker hub location - https://hub.docker.com/r/cockroachdb/replicator (#860)
- [ ] Ensure @bobvawter and @BramGruneir are admins on this new hub

**Comment by BramGruneir** [comment]
I think we're done here.  Closing this out.
